# File: .github/workflows/azure-deploy.yml

name: Build and deploy Python app to Azure Web App - Beesdetectionmiddefence

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      contents: read

    steps:
      - uses: actions/checkout@v4

      - name: Set up Python version
        uses: actions/setup-python@v5
        with:
          python-version: '3.10'

      - name: Test dependencies locally (optional)
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Upload artifact for deployment
        uses: actions/upload-artifact@v4
        with:
          name: python-app
          path: .

  deploy:
    runs-on: ubuntu-latest
    needs: build
    permissions:
      id-token: write
      contents: read

    steps:
      - name: Download artifact from build job
        uses: actions/download-artifact@v4
        with:
          name: python-app

      - name: Login to Azure
        uses: azure/login@v2
        with:
          client-id: ${{ secrets.AZUREAPPSERVICE_CLIENTID_47B81FEAABBF4F3FB029A2222F2328E8 }}
          tenant-id: ${{ secrets.AZUREAPPSERVICE_TENANTID_219BBF646EBE4B478D0F84B970EEC9B2 }}
          subscription-id: ${{ secrets.AZUREAPPSERVICE_SUBSCRIPTIONID_AA5B710807934595AEB864A32B5F8869 }}

      - name: Deploy to Azure Web App
        uses: azure/webapps-deploy@v3
        id: deploy-to-webapp
        with:
          app-name: 'Beesdetectionmiddefence'
          slot-name: 'Production'
